version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /node/app/node_modules
      - .:/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /node/app/node_modules
      - .:/node/app
    command: [ "npm", "run", "test" ]
